GET http://localhost:3001/test HTTP/1.1

###

POST http://localhost:3001/users/booking/9876/1234 HTTP/1.1
content-type: application/json

{
    "slot":"9 AM to 10 AM",
    "dateOfAppointment":"2020-09-03"
}